FROM python:3.10-slim as wsgi-server

RUN apt update \
    && apt install -y --no-install-recommends python3-dev default-libmysqlclient-dev build-essential libpq-dev dos2unix \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

COPY . .

RUN python manage.py check --deploy \
    && python manage.py collectstatic --no-input \
    && dos2unix entrypoint.sh \
    && chmod +x entrypoint.sh



FROM nginx:1.22-alpine as web-server

WORKDIR /app

COPY --from=wsgi-server /app/static /app/static

COPY nginx.conf /etc/nginx/templates/default.conf.template
